### PR TITLE
Enabled documentation file generating

### PR DESCRIPTION
**Pull request by kysel**
✅ xml file is included in NuGet package and thus VS shows documentation

### CODE REVIEW

**Comment by matkoch** [comment]
I haven't checked in a long time, but isn't it [this](https://github.com/nuke-build/common/blob/develop/source/Directory.Build.props#L30)?

**Comment by kysel** [comment]
That may be obsolete and safely deleted now (nope, see end of comment and last commit). NuGet package currently does not contain documentation (only .dll in lib folder). [see SO answer](https://stackoverflow.com/a/52986694/3976133)
I've replaced the pointed line with `GenerateDocumentationFile` property and also update the conditions which, I believe, caused all the troubles.

**Comment by matkoch** [comment]
So `IsPackable` is no longer defaulted to `True`?

**Comment by kysel** [comment]
Last version of Nuke that contained documentation was 0.14.1. I'll look into diff what's chaged since then.

**Comment by matkoch** [comment]
I'm really curious what has changed [between 0.11.1 and 0.12.0](https://github.com/nuke-build/common/compare/0.11.1...0.12.0) that caused the documentation file to disappear.

**Comment by matkoch** [comment]
Ah true, from 0.14.1 to 0.15.0 too. It's probably https://github.com/nuke-build/common/commit/0d55bb17a15ae44c539e31f46b5aee5f401d7303

**Comment by matkoch** [comment]
Thanks for noticing!

**Comment by kysel** [comment]
NP, thanks for fast PR merge 👍

**Pull request merged**
